CREATE MEMORY TABLE VEND(VEND_NAME VARCHAR(20) NOT NULL PRIMARY KEY,VEND_DIV VARCHAR(5) NOT NULL,VEND_REP VARCHAR(10), VEND_NUM VARCHAR(20), VEND_CONDITION VARCHAR(20), VEND_JONGMOK VARCHAR(20), VEND_ADDR VARCHAR(20), VEND_PHONE_NUM VARCHAR(20), VEND_FAX_NUM VARCHAR(20), VEND_MAIL_ADDR VARCHAR(20))
SET WRITE_DELAY 20
SET SCHEMA PUBLIC
INSERT INTO VEND VALUES('$VEND_NAME$','1','$VEND_REP$','$VEND_NUM$','$VEND_CONDITION$','$VEND_JONGMOK$','$VEND_ADDR$','$VEND_PHONE_NUM$','$VEND_FAX_NUM$','$VEND_MAIL_ADDR$')